### ISSUE TITLE
Cura 2.7

### ISSUE THREAD

**Issue by modem7** [MoonCactus/gcode_postprocessors#4]
Hello, 

Is there any method of getting this plugin to run in cura 2.7 at all?

Thanks!

**Comment by MoonCactus** [comment]
Sorry for the super late answer, but this is still on my list.
Sorry also as I will probably not "fix" this issue as long as Ultimaker changes its mind: Cura keeps on breaking its own plugin support...

Seriously, it never settled long enough for me to tackle the issue. E.g. it just happened once more for the forthcoming Cura 4. In addition, it will now require approval from Ultimaker from now on, so it is even more annoying and time-consuming (though somehow understandable).
So for now, I just keep the bug open. Maybe Cura will settle at some point and I can spend time on it again. I would be to spend time on "fixing" my plugin with no warranty they do not break it again on the next release :/

The other option that worked since day one is to use Python and run the script on the STL by yourself, as always. It is not convenient, but it is functional and stable in the long term :/
